language: node_js
sudo: false
dist: trusty
install:
  - npm install
cache:
  directories:
    - node_modules
addons:
  chrome: stable
# http://www.jackpu.com/jie-jue-karma-zai-travis-zhao-bu-dao-chrome_binde-wen-ti/
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test
  - npm run build:exam
after_script:
  - cd ./public
  - git config user.name "jessezhao1990"
  - git config user.email "215696013@qq.com"
  - git clone git@github.com:JesseZhao1990/JesseZhao1990.github.io.git
  - rm -rf ./JesseZhao1990.github.io/vue-lazy-load-list
  - cp -r  /home/travis/build/JesseZhao1990/vue-lazy-load-list/dist   ./JesseZhao1990.github.io/vue-lazy-load-list
  - cd JesseZhao1990.github.io
  - touch test.txt
  - git add .
  - git commit -m "update"
  - git push --force --quiet
branches:
  only:
  - master
node_js:
  - '8'
